[home]
    href = 'home'
    icon = 'mdi-home'
    text = 'Home'
    logged_in = false
    visibility = true
[athena]
    href = 'athena'
    icon = 'mdi-robot'
    text = 'Athena'
    logged_in = false
    visibility = true

[personas]
    href = 'user/personas'
    icon = 'mdi-account'
    text = 'Personas'
    logged_in = false
    visibility = true

[chat_with_llms]
    href = 'chat-with-llms'
    icon = 'mdi-message'
    text = 'Chat with LLMs'
    logged_in = false
    visibility = true
[docs]
    href = 'docs'
    icon = 'mdi-book-multiple-variant'
    text = 'Docs'
    logged_in = false
    visibility = true
[content]
    href = 'content'
    icon = 'mdi-security'
    text = 'Security content'
    logged_in = false
    visibility = true
[videos]
    href = 'content/videos'
    icon = 'mdi-video'
    text = 'Videos'
    logged_in = false
    visibility = true
[community_discord]
    href      = 'https://discord.gg/HdJJbFpzMX'
    icon      = 'mdi-message'
    text      = 'Community (Discord)'
    logged_in = false
    visibility = true
    new_window = true
